/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class EventSchema extends BaseModel {
  static $columns = ['banner', 'createdAt', 'description', 'eventId', 'location', 'organizerContact', 'ownerId', 'registrationEndAt', 'registrationStartAt', 'slug', 'status', 'title', 'updatedAt'] as const
  $columns = EventSchema.$columns
  @column()
  declare banner: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare description: string | null
  @column()
  declare eventId: string
  @column()
  declare location: string
  @column()
  declare organizerContact: string
  @column()
  declare ownerId: string
  @column.dateTime()
  declare registrationEndAt: DateTime
  @column.dateTime()
  declare registrationStartAt: DateTime
  @column()
  declare slug: string | null
  @column()
  declare status: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'password', 'role', 'updatedAt', 'userId'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: string
}
